import { NextResponse } from "next/server";

import { toCsvLine } from "@/lib/csv";
import { listInventoryGlobalEntries } from "@/lib/repositories";
import { getSession } from "@/lib/session";

const HEADER = [
  "id",
  "mainSku",
  "variantSku",
  "batch",
  "batchNoSn",
  "goodToReleaseShipmentFromCm",
  "status",
  "description",
  "stockQtyAvailableForFulfillment",
  "reservedQty",
  "batchesBalanceQty",
  "mpBatchProducedQty",
  "dkksFactory",
  "huiliFactory",
  "bolanFactory",
  "jiadunFactory",
  "jinjianFactory",
  "huameiFactory",
  "shenzhenOffice",
  "taiwanFuhshing",
  "singaporeOffice",
  "cargohubWarehouse",
  "koreaSolityFactory",
  "vietnamSolityFactory",
  "aztechFactory",
  "swrFactory",
  "vsFactory",
  "ibeFactory",
  "smartWarehousing",
  "omniWarehouse",
  "amazonFba",
  "safetyStockAtAmazon",
  "jdmWarehouse",
  "amazon",
  "syw",
  "inTransitStock",
  "inventoryReceivedDate",
  "agingDaysC",
  "unitPriceRmb",
  "unitPriceUsd",
  "batchesInventoryCostUsd",
  "skuInventoryCostUsd",
  "chinaInventoryCostUsd",
  "singaporeInventoryCostUsd",
  "singaporeCargohubInventoryCostUsd",
  "koreaSolityInventoryCost",
  "vietnamSolityInventoryCostUsd",
  "usaOmniInventoryVostUsd",
  "usAmazonFba",
  "europeJdmInventoryCostUsd",
  "inTransitInventoryCostUsd",
  "createdBy",
  "createdAt",
  "updatedAt",
];

export async function GET() {
  const session = await getSession();
  if (!session) return NextResponse.json({ message: "Unauthorized" }, { status: 401 });

  const entries = await listInventoryGlobalEntries();
  const lines = [toCsvLine(HEADER)];
  for (const e of entries) {
    lines.push(
      toCsvLine([
        e.id,
        e.mainSku,
        e.variantSku,
        e.batch,
        e.batchNoSn,
        e.goodToReleaseShipmentFromCm,
        e.status,
        e.description,
        e.stockQtyAvailableForFulfillment,
        e.reservedQty,
        e.batchesBalanceQty,
        e.mpBatchProducedQty,
        e.dkksFactory,
        e.huiliFactory,
        e.bolanFactory,
        e.jiadunFactory,
        e.jinjianFactory,
        e.huameiFactory,
        e.shenzhenOffice,
        e.taiwanFuhshing,
        e.singaporeOffice,
        e.cargohubWarehouse,
        e.koreaSolityFactory,
        e.vietnamSolityFactory,
        e.aztechFactory,
        e.swrFactory,
        e.vsFactory,
        e.ibeFactory,
        e.smartWarehousing,
        e.omniWarehouse,
        e.amazonFba,
        e.safetyStockAtAmazon,
        e.jdmWarehouse,
        e.amazon,
        e.syw,
        e.inTransitStock,
        e.inventoryReceivedDate ?? "",
        e.agingDaysC,
        e.unitPriceRmb,
        e.unitPriceUsd,
        e.batchesInventoryCostUsd,
        e.skuInventoryCostUsd,
        e.chinaInventoryCostUsd,
        e.singaporeInventoryCostUsd,
        e.singaporeCargohubInventoryCostUsd,
        e.koreaSolityInventoryCost,
        e.vietnamSolityInventoryCostUsd,
        e.usaOmniInventoryVostUsd,
        e.usAmazonFba,
        e.europeJdmInventoryCostUsd,
        e.inTransitInventoryCostUsd,
        e.createdBy,
        e.createdAt,
        e.updatedAt,
      ]),
    );
  }

  const filename = `inventory-global-${new Date().toISOString().slice(0, 10)}.csv`;
  return new NextResponse(lines.join("\n"), {
    status: 200,
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}
