import { NextResponse } from "next/server";

import { toCsvLine } from "@/lib/csv";
import { getSession } from "@/lib/session";

const HEADER = [
  "mainSku",
  "variantSku",
  "batch",
  "batchNoSn",
  "goodToReleaseShipmentFromCm",
  "status",
  "description",
  "stockQtyAvailableForFulfillment",
  "reservedQty",
  "batchesBalanceQty",
  "mpBatchProducedQty",
  "dkksFactory",
  "huiliFactory",
  "bolanFactory",
  "jiadunFactory",
  "jinjianFactory",
  "huameiFactory",
  "shenzhenOffice",
  "taiwanFuhshing",
  "singaporeOffice",
  "cargohubWarehouse",
  "koreaSolityFactory",
  "vietnamSolityFactory",
  "aztechFactory",
  "swrFactory",
  "vsFactory",
  "ibeFactory",
  "smartWarehousing",
  "omniWarehouse",
  "amazonFba",
  "safetyStockAtAmazon",
  "jdmWarehouse",
  "amazon",
  "syw",
  "inTransitStock",
  "inventoryReceivedDate",
  "agingDaysC",
  "unitPriceRmb",
  "unitPriceUsd",
  "batchesInventoryCostUsd",
  "skuInventoryCostUsd",
  "chinaInventoryCostUsd",
  "singaporeInventoryCostUsd",
  "singaporeCargohubInventoryCostUsd",
  "koreaSolityInventoryCost",
  "vietnamSolityInventoryCostUsd",
  "usaOmniInventoryVostUsd",
  "usAmazonFba",
  "europeJdmInventoryCostUsd",
  "inTransitInventoryCostUsd",
];

const EXAMPLE = [
  "IGB4",
  "IGB4-BLE",
  "B1",
  "",
  "0",
  "Ready",
  "",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "2026-03-31",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
  "0",
];

export async function GET() {
  const session = await getSession();
  if (!session) return NextResponse.json({ message: "Unauthorized" }, { status: 401 });

  const csv = [toCsvLine(HEADER), toCsvLine(EXAMPLE)].join("\n");
  return new NextResponse(csv, {
    status: 200,
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": 'attachment; filename="inventory-global-import-template.csv"',
      "Cache-Control": "no-store",
    },
  });
}
